FEATURE_NAMES = [
    '0_Absolute energy',
    '0_Area under the curve',
    '0_Autocorrelation',
    '0_Average power',
    '0_Centroid',
    '0_ECDF Percentile Count_0',
    '0_ECDF Percentile Count_1',
    '0_ECDF Percentile_0',
    '0_ECDF Percentile_1',
    '0_Entropy',
    '0_Histogram mode',
    '0_Interquartile range',
    '0_Kurtosis',
    '0_Max',
    '0_Mean',
    '0_Mean absolute deviation',
    '0_Mean absolute diff',
    '0_Mean diff',
    '0_Median',
    '0_Median absolute deviation',
    '0_Median absolute diff',
    '0_Median diff',
    '0_Min',
    '0_Negative turning points',
    '0_Neighbourhood peaks',
    '0_Peak to peak distance',
    '0_Positive turning points',
    '0_Root mean square',
    '0_Signal distance',
    '0_Skewness',
    '0_Slope',
    '0_Standard deviation',
    '0_Sum absolute diff',
    '0_Variance',
    '0_Zero crossing rate',
    '0_Fundamental frequency',
    '0_Human range energy',
    '0_Max power spectrum',
    '0_Maximum frequency',
    '0_Median frequency',
    '0_Power bandwidth',
    '0_Wavelet entropy',
    'value_median',
    'value_mean',
    'value_qmean',
    'value_max',
    'value_min',
    'value_maxmin',
    'value_diffmax',
    'value_diffmin',
    'value_diffmean',
    'value_diffqmean',
    'value_diffmedian',
    'value_diffmaxmin',
    'time_diffmean',
    'time_diffqmean',
    'time_diffmax',
    'time_diffmin',
    'time_diffmedian',
    'value_std',
    'value_var',
    'value_diffstd',
    'value_diffvar',
    'time_diffstd',
    'time_diffvar',
    'time_burstiness',
    'time_total',
    'time_event_density',
    'time_entropy',
    'time_slope'
]