FEATURE_NAMES = [
    '0_Absolute energy',
    '0_Area under the curve',
    '0_Autocorrelation',
    '0_Average power',
    '0_Centroid',
    '0_ECDF Percentile Count_0',
    '0_ECDF Percentile Count_1',
    '0_ECDF Percentile_0',
    '0_ECDF Percentile_1',
    '0_ECDF_0',
    '0_ECDF_1',
    '0_ECDF_2',
    '0_ECDF_3',
    '0_ECDF_4',
    '0_ECDF_5',
    '0_ECDF_6',
    '0_ECDF_7',
    '0_ECDF_8',
    '0_ECDF_9',
    '0_Entropy',
    '0_Histogram mode',
    '0_Interquartile range',
    '0_Kurtosis',
    '0_Max',
    '0_Mean',
    '0_Mean absolute deviation',
    '0_Mean absolute diff',
    '0_Mean diff',
    '0_Median',
    '0_Median absolute deviation',
    '0_Median absolute diff',
    '0_Median diff',
    '0_Min',
    '0_Negative turning points',
    '0_Neighbourhood peaks',
    '0_Peak to peak distance',
    '0_Positive turning points',
    '0_Root mean square',
    '0_Signal distance',
    '0_Skewness',
    '0_Slope',
    '0_Standard deviation',
    '0_Sum absolute diff',
    '0_Variance',
    '0_Zero crossing rate',
    '0_Fundamental frequency',
    '0_Human range energy',
    '0_Max power spectrum',
    '0_Maximum frequency',
    '0_Median frequency',
    '0_Power bandwidth',
    '0_Spectral centroid',
    '0_Spectral decrease',
    '0_Spectral distance',
    '0_Spectral entropy',
    '0_Spectral kurtosis',
    '0_Spectral positive turning points',
    '0_Spectral roll-off',
    '0_Spectral roll-on',
    '0_Spectral skewness',
    '0_Spectral slope',
    '0_Spectral spread',
    '0_Spectral variation',
    '0_Spectrogram mean coefficient_0.0Hz',
    '0_Spectrogram mean coefficient_1.03Hz',
    '0_Spectrogram mean coefficient_10.31Hz',
    '0_Spectrogram mean coefficient_11.34Hz',
    '0_Spectrogram mean coefficient_12.37Hz',
    '0_Spectrogram mean coefficient_13.4Hz',
    '0_Spectrogram mean coefficient_14.44Hz',
    '0_Spectrogram mean coefficient_15.47Hz',
    '0_Spectrogram mean coefficient_16.5Hz',
    '0_Spectrogram mean coefficient_17.53Hz',
    '0_Spectrogram mean coefficient_18.56Hz',
    '0_Spectrogram mean coefficient_19.59Hz',
    '0_Spectrogram mean coefficient_2.06Hz',
    '0_Spectrogram mean coefficient_20.62Hz',
    '0_Spectrogram mean coefficient_21.65Hz',
    '0_Spectrogram mean coefficient_22.68Hz',
    '0_Spectrogram mean coefficient_23.72Hz',
    '0_Spectrogram mean coefficient_24.75Hz',
    '0_Spectrogram mean coefficient_25.78Hz',
    '0_Spectrogram mean coefficient_26.81Hz',
    '0_Spectrogram mean coefficient_27.84Hz',
    '0_Spectrogram mean coefficient_28.87Hz',
    '0_Spectrogram mean coefficient_29.9Hz',
    '0_Spectrogram mean coefficient_3.09Hz',
    '0_Spectrogram mean coefficient_30.93Hz',
    '0_Spectrogram mean coefficient_31.97Hz',
    '0_Spectrogram mean coefficient_4.12Hz',
    '0_Spectrogram mean coefficient_5.16Hz',
    '0_Spectrogram mean coefficient_6.19Hz',
    '0_Spectrogram mean coefficient_7.22Hz',
    '0_Spectrogram mean coefficient_8.25Hz',
    '0_Spectrogram mean coefficient_9.28Hz',
    '0_Wavelet absolute mean_1.78Hz',
    '0_Wavelet absolute mean_15.98Hz',
    '0_Wavelet absolute mean_2.0Hz',
    '0_Wavelet absolute mean_2.28Hz',
    '0_Wavelet absolute mean_2.66Hz',
    '0_Wavelet absolute mean_3.2Hz',
    '0_Wavelet absolute mean_4.0Hz',
    '0_Wavelet absolute mean_5.33Hz',
    '0_Wavelet absolute mean_7.99Hz',
    '0_Wavelet energy_1.78Hz',
    '0_Wavelet energy_15.98Hz',
    '0_Wavelet energy_2.0Hz',
    '0_Wavelet energy_2.28Hz',
    '0_Wavelet energy_2.66Hz',
    '0_Wavelet energy_3.2Hz',
    '0_Wavelet energy_4.0Hz',
    '0_Wavelet energy_5.33Hz',
    '0_Wavelet energy_7.99Hz',
    '0_Wavelet entropy',
    '0_Wavelet standard deviation_1.78Hz',
    '0_Wavelet standard deviation_15.98Hz',
    '0_Wavelet standard deviation_2.0Hz',
    '0_Wavelet standard deviation_2.28Hz',
    '0_Wavelet standard deviation_2.66Hz',
    '0_Wavelet standard deviation_3.2Hz',
    '0_Wavelet standard deviation_4.0Hz',
    '0_Wavelet standard deviation_5.33Hz',
    '0_Wavelet standard deviation_7.99Hz',
    '0_Wavelet variance_1.78Hz',
    '0_Wavelet variance_15.98Hz',
    '0_Wavelet variance_2.0Hz',
    '0_Wavelet variance_2.28Hz',
    '0_Wavelet variance_2.66Hz',
    '0_Wavelet variance_3.2Hz',
    '0_Wavelet variance_4.0Hz',
    '0_Wavelet variance_5.33Hz',
    '0_Wavelet variance_7.99Hz',
    'value_count',
    'value_median',
    'value_mean',
    'value_qmean',
    'value_max',
    'value_min',
    'value_maxmin',
    'value_std',
    'value_var',
    'value_diffstd',
    'value_diffvar',
    'value_diffmax',
    'value_diffmin',
    'value_diffmean',
    'value_diffqmean',
    'value_diffmedian',
    'value_diffmaxmin',
    'time_diffmean',
    'time_diffqmean',
    'time_diffmax',
    'time_diffmin',
    'time_diffmedian',
    'time_diffstd',
    'time_diffvar',
    'time_burstiness',
    'time_total',
    'time_event_density',
    'time_entropy',
    'time_slope'
]
# FEATURE_NAMES = [
#     '0_Absolute energy',
#     '0_Area under the curve',
#     '0_Autocorrelation',
#     '0_Average power',
#     '0_Centroid',
#     '0_ECDF Percentile Count_0',
#     '0_ECDF Percentile Count_1',
#     '0_ECDF Percentile_0',
#     '0_ECDF Percentile_1',
#     '0_Entropy',
#     '0_Histogram mode',
#     '0_Interquartile range',
#     '0_Kurtosis',
#     '0_Max',
#     '0_Mean',
#     '0_Mean absolute deviation',
#     '0_Mean absolute diff',
#     '0_Mean diff',
#     '0_Median',
#     '0_Median absolute deviation',
#     '0_Median absolute diff',
#     '0_Median diff',
#     '0_Min',
#     '0_Negative turning points',
#     '0_Neighbourhood peaks',
#     '0_Peak to peak distance',
#     '0_Positive turning points',
#     '0_Root mean square',
#     '0_Signal distance',
#     '0_Skewness',
#     '0_Slope',
#     '0_Standard deviation',
#     '0_Sum absolute diff',
#     '0_Variance',
#     '0_Zero crossing rate',
#     '0_Fundamental frequency',
#     '0_Human range energy',
#     '0_Max power spectrum',
#     '0_Maximum frequency',
#     '0_Median frequency',
#     '0_Power bandwidth',
#     '0_Wavelet entropy',
#     'value_median',
#     'value_mean',
#     'value_qmean',
#     'value_max',
#     'value_min',
#     'value_maxmin',
#     'value_diffmax',
#     'value_diffmin',
#     'value_diffmean',
#     'value_diffqmean',
#     'value_diffmedian',
#     'value_diffmaxmin',
#     'time_diffmean',
#     'time_diffqmean',
#     'time_diffmax',
#     'time_diffmin',
#     'time_diffmedian',
#     'value_std',
#     'value_var',
#     'value_diffstd',
#     'value_diffvar',
#     'time_diffstd',
#     'time_diffvar',
#     'time_burstiness',
#     'time_total',
#     'time_event_density',
#     'time_entropy',
#     'time_slope'
# ]