_target_: src.models.brick_cls_module.BrickClsModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.transformer.spectrogram_classifier.Classifier
  encoder:
    _target_: src.models.transformer.spectrogram_encoder.TransformerEncoder
    model_dim: 256
    num_heads: 8
    num_layers: 16
    ff_dim: 512
    patch_size: 5
    dropout: 0.1
  n_classes: 94
  hidden_dim: 512

# compile model for faster training with pytorch 2.0
compile: false
